set -x
circle dynamic_names.cxx
circle enum_dispatch.cxx
circle enum_dispatch2.cxx
circle enums.cxx
circle eprintf.cxx
circle hello.cxx
circle inject.cxx
# circle inject2.cxx 
circle peg_dsl.cxx
circle rpn.cxx
circle serialization.cxx
circle shapes.cxx
circle tuple.cxx
circle typed_enums.cxx
circle typed_enums2.cxx
circle typed_enums3.cxx
circle unique.cxx
circle variant.cxx