set -x
circle iterate.cxx && ./iterate
circle pack1.cxx && ./pack1
circle pack2.cxx && ./pack2
circle slice.cxx && ./slice
circle range.cxx && ./range
circle for.cxx && ./for
circle locus.cxx && ./locus
circle expansion.cxx && ./expansion
circle list_comp.cxx && ./list_comp
circle locus2.cxx && ./locus2
circle fold.cxx && ./fold
circle range_for.cxx && ./range_for
circle sequences.cxx && ./sequences
circle slice2.cxx && ./slice2
circle pack_decl.cxx && ./pack_decl
circle hello.cxx && ./hello
circle any_of.cxx && ./any_of
circle count.cxx && ./count
circle count_if.cxx && ./count_if
circle for_each.cxx && ./for_each
circle for_each2.cxx && ./for_each2
circle is_sorted.cxx && ./is_sorted
circle filter.cxx && ./filter
circle accumulate.cxx && ./accumulate
circle comprehension.cxx && ./comprehension
