set -x
circle pattern1.cxx
circle pattern2.cxx
circle pattern3.cxx
circle pattern4.cxx
circle pattern5.cxx
circle pattern6.cxx
circle pattern7.cxx
circle pattern8.cxx
circle pattern9.cxx
circle pattern10.cxx
circle pattern11.cxx
